### ISSUE TITLE
transferData or transfer-data?

### ISSUE THREAD

**Issue by thyerrimezzari** [cameronhimself/vue-drag-drop-demo#3]
The transferData property did not work for me. I checked the demo files and found the property like this: transfer-data. That way (trasnfer-date) worked for me. What is the difference between transferData and transfer-date?

**Comment by cameronhimself** [comment]
This is an issue with my documentation and examples--you should only use kebab-case properties in Vue templates. It's a bit strange that it doesn't work at all--it should only throw a warning if you have certain Vue dev tools open--but regardless it should be corrected.

Since there's already an [open issue](https://github.com/cameronhimself/vue-drag-drop/issues/14) for this on the main repo, I'm going to close this. Thank you for reporting!
